### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by drewgash** [inubushi/LSTM-KTH#3]
Hi Chamin,

I receive this error when attempting to run training:

```
model.fit(np.array(X_train), y_train, batch_size=batch_size, nb_epoch=nb_epochs, shuffle=True, verbose=1)
Traceback (most recent call last):
  File "KTH_LSTM.py", line 186, in <module>
    model.fit(np.array(X_train), y_train, batch_size=batch_size, nb_epoch=nb_epochs, shuffle=True, verbose=1)
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 950, in fit
    batch_size=batch_size)
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\drewgash\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_utils.py", line 127, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected time_distributed_1_input to have 5 dimensions, but got array with shape (2400, 1) 
```

Please help. Also if you have a saved weight somewhere that would be great.

**Comment by inubushi** [comment]
Hi,

Sorry for the delay. It has been a while since I did this work but I might be able to find saved weights. Will also check why the dimensions are not correct. If I remember right, 2400 was the number of training samples.

**Comment by drewgash** [comment]
Thanks. It would be greatly appreciated.

**Comment by inubushi** [comment]
https://www.dropbox.com/s/tde9xsbmr2gr6xc/kth6_95.50.hdf5?dl=0 Herewith find the weights that I saved earlier. If there is a problem with loading them, let me know and I will re-run the code to see where the error is coming from.

**Comment by drewgash** [comment]
Thanks Chamin. I will let you know how it goes.
